export const Lists = (listName) => {

  let countries = [
    { value: "Åland Islands", label: "Åland Islands" },
    { value: "Afghanistan", label: "Afghanistan" },
    { value: "Akrotiri", label: "Akrotiri" },
    { value: "Albania", label: "Albania" },
    { value: "Algeria", label: "Algeria" },
    { value: "American Samoa", label: "American Samoa" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Anguilla", label: "Anguilla" },
    { value: "Antarctica", label: "Antarctica" },
    { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Armenia" },
    { value: "Aruba", label: "Aruba" },
    { value: "Ashmore and Cartier Islands", label: "Ashmore and Cartier Islands" },
    { value: "Australia", label: "Australia" },
    { value: "Austria", label: "Austria" },
    { value: "Azerbaijan", label: "Azerbaijan" },
    { value: "Bahrain", label: "Bahrain" },
    { value: "Bangladesh", label: "Bangladesh" },
    { value: "Barbados", label: "Barbados" },
    { value: "Bassas Da India", label: "Bassas Da India" },
    { value: "Belarus", label: "Belarus" },
    { value: "Belgium", label: "Belgium" },
    { value: "Belize", label: "Belize" },
    { value: "Benin", label: "Benin" },
    { value: "Bermuda", label: "Bermuda" },
    { value: "Bhutan", label: "Bhutan" },
    { value: "Bolivia", label: "Bolivia" },
    { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
    { value: "Botswana", label: "Botswana" },
    { value: "Bouvet Island", label: "Bouvet Island" },
    { value: "Brazil", label: "Brazil" },
    { value: "British Indian Ocean Territory", label: "British Indian Ocean Territory" },
    { value: "British Virgin Islands", label: "British Virgin Islands" },
    { value: "Brunei", label: "Brunei" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burma", label: "Burma" },
    { value: "Burundi", label: "Burundi" },
    { value: "Cambodia", label: "Cambodia" },
    { value: "Cameroon", label: "Cameroon" },
    { value: "Canada", label: "Canada" },
    { value: "Cape Verde", label: "Cape Verde" },
    { value: "Caribbean Netherlands", label: "Caribbean Netherlands" },
    { value: "Cayman Islands", label: "Cayman Islands" },
    { value: "Central African Republic", label: "Central African Republic" },
    { value: "Chad", label: "Chad" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Christmas Island", label: "Christmas Island" },
    { value: "Clipperton Island", label: "Clipperton Island" },
    { value: "Cocos (Keeling) Islands", label: "Cocos (Keeling) Islands" },
    { value: "Colombia", label: "Colombia" },
    { value: "Comoros", label: "Comoros" },
    { value: "Cook Islands", label: "Cook Islands" },
    { value: "Coral Sea Islands", label: "Coral Sea Islands" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Cote D'Ivoire", label: "Cote D'Ivoire" },
    { value: "Croatia", label: "Croatia" },
    { value: "Cuba", label: "Cuba" },
    { value: "Curaçao", label: "Curaçao" },
    { value: "Cyprus", label: "Cyprus" },
    { value: "Czech Republic", label: "Czech Republic" },
    { value: "Democratic Republic of the Congo", label: "Democratic Republic of the Congo" },
    { value: "Denmark", label: "Denmark" },
    { value: "Dhekelia", label: "Dhekelia" },
    { value: "Djibouti", label: "Djibouti" },
    { value: "Dominica", label: "Dominica" },
    { value: "Dominican Republic", label: "Dominican Republic" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Egypt", label: "Egypt" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Equatorial Guinea", label: "Equatorial Guinea" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Estonia", label: "Estonia" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Europa Island", label: "Europa Island" },
    { value: "Falkland Islands (Islas Malvinas)", label: "Falkland Islands (Islas Malvinas)" },
    { value: "Faroe Islands", label: "Faroe Islands" },
    { value: "Federated States of Micronesia", label: "Federated States of Micronesia" },
    { value: "Fiji", label: "Fiji" },
    { value: "Finland", label: "Finland" },
    { value: "France", label: "France" },
    { value: "French Guiana", label: "French Guiana" },
    { value: "French Polynesia", label: "French Polynesia" },
    { value: "French Southern and Antarctic Lands", label: "French Southern and Antarctic Lands" },
    { value: "Gabon", label: "Gabon" },
    { value: "Gaza Strip", label: "Gaza Strip" },
    { value: "Georgia", label: "Georgia" },
    { value: "Germany", label: "Germany" },
    { value: "Ghana", label: "Ghana" },
    { value: "Gibraltar", label: "Gibraltar" },
    { value: "Glorioso Islands", label: "Glorioso Islands" },
    { value: "Greece", label: "Greece" },
    { value: "Greenland", label: "Greenland" },
    { value: "Grenada", label: "Grenada" },
    { value: "Guadeloupe", label: "Guadeloupe" },
    { value: "Guam", label: "Guam" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guernsey", label: "Guernsey" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea-bissau", label: "Guinea-bissau" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
    { value: "Heard Island and Mcdonald Islands", label: "Heard Island and Mcdonald Islands" },
    { value: "Holy See (Vatican City)", label: "Holy See (Vatican City)" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hong Kong", label: "Hong Kong" },
    { value: "Hungary", label: "Hungary" },
    { value: "Iceland", label: "Iceland" },
    { value: "India", label: "India" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Iran", label: "Iran" },
    { value: "Iraq", label: "Iraq" },
    { value: "Ireland", label: "Ireland" },
    { value: "Isle of Man", label: "Isle of Man" },
    { value: "Israel", label: "Israel" },
    { value: "Italy", label: "Italy" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Jan Mayen", label: "Jan Mayen" },
    { value: "Japan", label: "Japan" },
    { value: "Jersey", label: "Jersey" },
    { value: "Jordan", label: "Jordan" },
    { value: "Juan De Nova Island", label: "Juan De Nova Island" },
    { value: "Kazakhstan", label: "Kazakhstan" },
    { value: "Kenya", label: "Kenya" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Kyrgyzstan", label: "Kyrgyzstan" },
    { value: "Laos", label: "Laos" },
    { value: "Latvia", label: "Latvia" },
    { value: "Lebanon", label: "Lebanon" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libya", label: "Libya" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Lithuania", label: "Lithuania" },
    { value: "Luxembourg", label: "Luxembourg" },
    { value: "Macau", label: "Macau" },
    { value: "Macedonia", label: "Macedonia" },
    { value: "Madagascar", label: "Madagascar" },
    { value: "Malawi", label: "Malawi" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Maldives", label: "Maldives" },
    { value: "Mali", label: "Mali" },
    { value: "Malta", label: "Malta" },
    { value: "Marshall Islands", label: "Marshall Islands" },
    { value: "Martinique", label: "Martinique" },
    { value: "Mauritania", label: "Mauritania" },
    { value: "Mauritius", label: "Mauritius" },
    { value: "Mayotte", label: "Mayotte" },
    { value: "Mexico", label: "Mexico" },
    { value: "Moldova", label: "Moldova" },
    { value: "Monaco", label: "Monaco" },
    { value: "Mongolia", label: "Mongolia" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Montserrat", label: "Montserrat" },
    { value: "Morocco", label: "Morocco" },
    { value: "Mozambique", label: "Mozambique" },
    { value: "Myanmar", label: "Myanmar" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Navassa Island", label: "Navassa Island" },
    { value: "Nepal", label: "Nepal" },
    { value: "Netherlands", label: "Netherlands" },
    { value: "Netherlands Antilles", label: "Netherlands Antilles" },
    { value: "New Caledonia", label: "New Caledonia" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Niue", label: "Niue" },
    { value: "Norfolk Island", label: "Norfolk Island" },
    { value: "North Korea", label: "North Korea" },
    { value: "Northern Mariana Islands", label: "Northern Mariana Islands" },
    { value: "Norway", label: "Norway" },
    { value: "Oman", label: "Oman" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Palau", label: "Palau" },
    { value: "Palestine", label: "Palestine" },
    { value: "Panama", label: "Panama" },
    { value: "Papua New Guinea", label: "Papua New Guinea" },
    { value: "Paracel Islands", label: "Paracel Islands" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Peru", label: "Peru" },
    { value: "Philippines", label: "Philippines" },
    { value: "Pitcairn Islands", label: "Pitcairn Islands" },
    { value: "Poland", label: "Poland" },
    { value: "Portugal", label: "Portugal" },
    { value: "Puerto Rico", label: "Puerto Rico" },
    { value: "Qatar", label: "Qatar" },
    { value: "Republic of the Congo", label: "Republic of the Congo" },
    { value: "Reunion", label: "Reunion" },
    { value: "Romania", label: "Romania" },
    { value: "Russia", label: "Russia" },
    { value: "Rwanda", label: "Rwanda" },
    { value: "Saint BarthÃ©lemy", label: "Saint BarthÃ©lemy" },
    { value: "Saint Helena", label: "Saint Helena" },
    { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
    { value: "Saint Lucia", label: "Saint Lucia" },
    { value: "Saint Martin", label: "Saint Martin" },
    { value: "Saint Pierre and Miquelon", label: "Saint Pierre and Miquelon" },
    { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
    { value: "Samoa", label: "Samoa" },
    { value: "San Marino", label: "San Marino" },
    { value: "Sao Tome and Principe", label: "Sao Tome and Principe" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Serbia" },
    { value: "Seychelles", label: "Seychelles" },
    { value: "Sierra Leone", label: "Sierra Leone" },
    { value: "Singapore", label: "Singapore" },
    { value: "Sint Maarten", label: "Sint Maarten" },
    { value: "Slovakia", label: "Slovakia" },
    { value: "Slovenia", label: "Slovenia" },
    { value: "Solomon Islands", label: "Solomon Islands" },
    { value: "Somalia", label: "Somalia" },
    { value: "South Africa", label: "South Africa" },
    { value: "South Georgia and the South Sandwich Islands", label: "South Georgia and the South Sandwich Islands" },
    { value: "South Korea", label: "South Korea" },
    { value: "South Sudan", label: "South Sudan" },
    { value: "Spain", label: "Spain" },
    { value: "Spratly Islands", label: "Spratly Islands" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Sudan", label: "Sudan" },
    { value: "Suriname", label: "Suriname" },
    { value: "Svalbard", label: "Svalbard" },
    { value: "Swaziland", label: "Swaziland" },
    { value: "Sweden", label: "Sweden" },
    { value: "Switzerland", label: "Switzerland" },
    { value: "Syria", label: "Syria" },
    { value: "Taiwan", label: "Taiwan" },
    { value: "Tajikistan", label: "Tajikistan" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Thailand", label: "Thailand" },
    { value: "The Bahamas", label: "The Bahamas" },
    { value: "The Gambia", label: "The Gambia" },
    { value: "Timor-leste", label: "Timor-leste" },
    { value: "Togo", label: "Togo" },
    { value: "Tokelau", label: "Tokelau" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
    { value: "Tromelin Island", label: "Tromelin Island" },
    { value: "Tunisia", label: "Tunisia" },
    { value: "Turkey", label: "Turkey" },
    { value: "Turkmenistan", label: "Turkmenistan" },
    { value: "Turks and Caicos Islands", label: "Turks and Caicos Islands" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Uganda", label: "Uganda" },
    { value: "Ukraine", label: "Ukraine" },
    { value: "United Arab Emirates", label: "United Arab Emirates" },
    { value: "United Kingdom", label: "United Kingdom" },
    { value: "United States", label: "United States" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Uzbekistan", label: "Uzbekistan" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Virgin Islands", label: "Virgin Islands" },
    { value: "Wake Island", label: "Wake Island" },
    { value: "Wallis and Futuna", label: "Wallis and Futuna" },
    { value: "West Bank", label: "West Bank" },
    { value: "Western Sahara", label: "Western Sahara" },
    { value: "Yemen", label: "Yemen" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabwe", label: "Zimbabwe" },
    { value: "Other", label: "Other" }
  ];//End countries

  let languages = [
    { value: "Aboriginal", label: "Aboriginal" },
    { value: "Arabic", label: "Arabic" },
    { value: "Bengali", label: "Bengali" },
    { value: "Burmese", label: "Burmese" },
    { value: "Cantonese", label: "Cantonese" },
    { value: "French", label: "French" },
    { value: "Greek", label: "Greek" },
    { value: "Hindi", label: "Hindi" },
    { value: "Indonesian", label: "Indonesian" },
    { value: "Italian", label: "Italian" },
    { value: "Lao", label: "Lao" },
    { value: "Lebanese Arabic", label: "Lebanese Arabic" },
    { value: "Macedonian", label: "Macedonian" },
    { value: "Malay", label: "Malay" },
    { value: "Mandarin", label: "Mandarin" },
    { value: "Oromo", label: "Oromo" },
    { value: "Punjabi", label: "Punjabi" },
    { value: "Sinhalese", label: "Sinhalese" },
    { value: "Spanish", label: "Spanish" },
    { value: "Swahili", label: "Swahili" },
    { value: "Tagalog", label: "Tagalog" },
    { value: "Tamil", label: "Tamil" },
    { value: "Thai", label: "Thai" },
    { value: "Vietnamese", label: "Vietnamese" },
    { value: "Other", label: "Other" }
  ];

  let states = [
    { label: 'NSW' },
    { label: 'VIC' },
    { label: 'QLD' },
    { label: 'WA' },
    { label: 'SA' },
    { label: 'NT' }
  ];

  let years_current = [
    { label: '2019' },
    { label: '2018' },
    { label: '2017' },
    { label: '2016' },
    { label: '2015' },
    { label: '2014' },
    { label: '2013' },
    { label: '2012' },
    { label: '2011' },
    { label: '2010' },
    { label: '2009' },
    { label: '2008' },
    { label: '2007' },
    { label: '2006' },
    { label: '2005' },
    { label: '2004' },
    { label: '2003' },
    { label: '2002' },
    { label: '2001' },
    { label: '2000' },
    { label: 'Before 2000' }
  ];

  let years = [
    { label: '2025' },
    { label: '2024' },
    { label: '2023' },
    { label: '2022' },
    { label: '2021' },
    { label: '2020' },
    { label: '2019' },
    { label: '2018' },
    { label: '2017' },
    { label: '2016' },
    { label: '2015' },
    { label: '2014' },
    { label: '2013' },
    { label: '2012' },
    { label: '2011' },
    { label: '2010' },
    { label: '2009' },
    { label: '2008' },
    { label: '2007' },
    { label: '2006' },
    { label: '2005' },
    { label: '2004' },
    { label: '2003' },
    { label: '2002' },
    { label: '2001' },
    { label: '2000' },
    { label: 'Before 2000' }
  ];

  let years_old = [
    { label: '2025' },
    { label: '2024' },
    { label: '2023' },
    { label: '2022' },
    { label: '2021' },
    { label: '2020' },
    { label: '2019' },
    { label: '2018' },
    { label: '2017' },
    { label: '2016' },
    { label: '2015' },
    { label: '2014' },
    { label: '2013' },
    { label: '2012' },
    { label: '2011' },
    { label: '2010' },
    { label: '2009' },
    { label: '2008' },
    { label: '2007' },
    { label: '2006' },
    { label: '2005' },
    { label: '2004' },
    { label: '2003' },
    { label: '2002' },
    { label: '2001' },
    { label: '2000' },
    { label: '1999' },
    { label: '1998' },
    { label: '1997' },
    { label: '1996' },
    { label: '1995' },
    { label: '1994' },
    { label: '1993' },
    { label: '1992' },
    { label: '1991' },
    { label: '1990' },
    { label: '1989' },
    { label: '1988' },
    { label: '1987' },
    { label: '1986' },
    { label: '1985' },
    { label: '1984' },
    { label: '1983' },
    { label: '1982' },
    { label: '1981' },
    { label: '1980' },
    { label: '1979' },
    { label: '1978' },
    { label: '1977' },
    { label: '1976' },
    { label: '1975' },
    { label: '1974' },
    { label: '1973' },
    { label: '1972' },
    { label: '1971' },
    { label: '1970' },
    { label: '1969' },
    { label: '1968' },
    { label: '1967' },
    { label: '1966' },
    { label: '1965' },
    { label: '1964' },
    { label: '1963' },
    { label: '1962' },
    { label: '1961' },
    { label: '1960' },
    { label: '1959' },
    { label: '1958' },
    { label: '1957' },
    { label: '1956' },
    { label: '1955' },
    { label: '1954' },
    { label: '1953' },
    { label: '1952' },
    { label: '1951' },
    { label: '1950' },
  ];

  if (listName === 'countries') {
    return countries;
  }//End if condition
  if (listName === 'states') {
    return states;
  }//End if condition
  if (listName === 'languages') {
    return languages;
  }//End if condition
  if (listName === 'years_current') {
    return years_current;
  }//End if condition
  if (listName === 'years') {
    return years;
  }//End if condition
  if (listName === 'years_old') {
    return years_old;
  }//End if condition



}//End Lists
